Repository googleapis/nodejs-game-servers, pull requests merged in 2020-03, with the labels that each got.

#17 build: get the build passing
  .github/publish.yml
  .github/workflows/ci.yaml
  .gitignore
  .jsdoc.js
  README.md
  linkinator.config.json
  package.json
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/test/quickstart.js
  src/index.ts
  synth.metadata
Labels: cla: yes

#18 build: get sample and system tests passing
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/release/docs.cfg
  .kokoro/release/publish.cfg
  README.md
  package.json
  samples/README.md
  samples/test/quickstart.js
  synth.metadata
Labels: cla: yes

#28 test: adds cleanup function for tests
  samples/get_realm.js
  samples/list_realms.js
  samples/test/clean.js
  samples/test/create_realm.test.js
  samples/test/delete_realm.test.js
  samples/test/get_realm.test.js
  samples/test/list_realms.test.js
  samples/test/quickstart.test.js
Labels: cla: yes

#25 build: update linkinator config
  linkinator.config.json
Labels: automerge, cla: yes, kokoro:force-run

#27 build(tests): fix coveralls and enable build cop
  .github/workflows/ci.yaml
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
Labels: automerge, cla: yes

#30 chore: remove snippet leading whitespace
  README.md
Labels: automerge, cla: yes

#34 chore: regenerate the code
  .github/workflows/ci.yaml
  .gitignore
  .jsdoc.js
  .repo-metadata.json
  README.md
  linkinator.config.json
  samples/README.md
  src/index.ts
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/index.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic-game_server_clusters_service-v1beta.ts
  test/gapic-game_server_configs_service-v1beta.ts
  test/gapic-game_server_deployments_service-v1beta.ts
  test/gapic-realms_service-v1beta.ts
  webpack.config.js
Labels: automerge, cla: yes

#37 feat!: drop node8 support
  .eslintrc.json
  .eslintrc.yml
  .github/workflows/ci.yaml
  .prettierrc
  .prettierrc.js
  package.json
  protos/google/cloud/gaming/v1beta/common.proto
  protos/google/cloud/gaming/v1beta/game_server_clusters.proto
  protos/google/cloud/gaming/v1beta/game_server_clusters_service.proto
  protos/google/cloud/gaming/v1beta/game_server_configs.proto
  protos/google/cloud/gaming/v1beta/game_server_configs_service.proto
  protos/google/cloud/gaming/v1beta/game_server_deployments.proto
  protos/google/cloud/gaming/v1beta/game_server_deployments_service.proto
  protos/google/cloud/gaming/v1beta/realms.proto
  protos/google/cloud/gaming/v1beta/realms_service.proto
  protos/protos.json
  src/index.ts
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  test/gapic-game_server_clusters_service-v1beta.ts
  test/gapic-game_server_configs_service-v1beta.ts
  test/gapic-game_server_deployments_service-v1beta.ts
  test/gapic-realms_service-v1beta.ts
  test/gapic_game_server_clusters_service_v1beta.ts
  test/gapic_game_server_configs_service_v1beta.ts
  test/gapic_game_server_deployments_service_v1beta.ts
  test/gapic_realms_service_v1beta.ts
  webpack.config.js
Labels: automerge, cla: yes
