Repository googleapis/nodejs-game-servers, pull requests merged in 2020-11, with the labels that each got.

#130 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full

#131 build: add v1.GameServerClustersServiceClient type
  src/index.ts
  synth.metadata
Labels: api: gameservices, cla: yes, context: none

#132 fix: do not modify options object, use defaultScopes
  package.json
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: gameservices, automerge, cla: yes

#136 fix(browser): check for fetch on window
  protos/protos.json
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
Labels: api: gameservices, cla: yes, context: partial

#138 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full
