Repository googleapis/nodejs-game-servers, pull requests merged in 2020-07, with the labels that each got.

#81 test: fix sample test by pointing at a shared cluster with Agones
  samples/test/create_cluster.test.js
  samples/test/delete_cluster.test.js
  samples/test/get_cluster.test.js
  samples/test/list_clusters.test.js
Labels: cla: yes

#80 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#79 fix: correct return type of delete operations
  protos/google/cloud/gaming/v1beta/common.proto
  protos/google/cloud/gaming/v1beta/game_server_clusters.proto
  protos/google/cloud/gaming/v1beta/game_server_clusters_service.proto
  protos/google/cloud/gaming/v1beta/game_server_configs.proto
  protos/google/cloud/gaming/v1beta/game_server_configs_service.proto
  protos/google/cloud/gaming/v1beta/game_server_deployments.proto
  protos/google/cloud/gaming/v1beta/game_server_deployments_service.proto
  protos/google/cloud/gaming/v1beta/realms.proto
  protos/google/cloud/gaming/v1beta/realms_service.proto
  protos/protos.json
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_clusters_service_client_config.json
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_configs_service_client_config.json
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/game_server_deployments_service_client_config.json
  src/v1beta/realms_service_client.ts
  src/v1beta/realms_service_client_config.json
  synth.metadata
  synth.py
  test/gapic_game_server_clusters_service_v1beta.ts
  test/gapic_game_server_configs_service_v1beta.ts
  test/gapic_game_server_deployments_service_v1beta.ts
  test/gapic_realms_service_v1beta.ts
Labels: cla: yes

#85 build: typo in gitattribute
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: cla: yes, context: partial

#87 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#88 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#89 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#94 docs(samples): fix sample formatting issues
  samples/create_cluster.js
  samples/create_realm.js
  samples/delete_cluster.js
  samples/delete_realm.js
  samples/get_cluster.js
  samples/get_realm.js
  samples/list_clusters.js
  samples/list_realms.js
Labels: cla: yes

#92 docs(samples): Add Game Server deployment samples
  samples/README.md
  samples/create_cluster.js
  samples/create_deployment.js
  samples/delete_deployment.js
  samples/get_deployment.js
  samples/list_deployments.js
  samples/package.json
  samples/test/crud_deployment.test.js
Labels: cla: yes

#97 docs(samples): Changed tags to be aligned with golang samples
  samples/create_cluster.js
  samples/create_deployment.js
  samples/create_realm.js
  samples/delete_cluster.js
  samples/delete_deployment.js
  samples/delete_realm.js
  samples/get_cluster.js
  samples/get_deployment.js
  samples/get_realm.js
  samples/list_clusters.js
  samples/list_deployments.js
  samples/list_realms.js
Labels: cla: yes

#100 chore: updates to readme, add Node8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#103 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#102 docs(samples): Add Sample for Game Server Rollout
  samples/get_rollout.js
  samples/test/rollout.js
  samples/update_rollout_default.js
  samples/update_rollout_override.js
  samples/update_rollout_remove_default.js
  samples/update_rollout_remove_override.js
Labels: cla: yes

#101 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#104 docs: update README with additional samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#105 build: update gitattributes and docs release scripts
  .gitattributes
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: partial

#106 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#107 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#108 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
