Repository googleapis/nodejs-game-servers, pull requests merged in 2020-08, with the labels that each got.

#109 feat: adds v1 API surface
  protos/google/cloud/gaming/v1/common.proto
  protos/google/cloud/gaming/v1/game_server_clusters.proto
  protos/google/cloud/gaming/v1/game_server_clusters_service.proto
  protos/google/cloud/gaming/v1/game_server_configs.proto
  protos/google/cloud/gaming/v1/game_server_configs_service.proto
  protos/google/cloud/gaming/v1/game_server_deployments.proto
  protos/google/cloud/gaming/v1/game_server_deployments_service.proto
  protos/google/cloud/gaming/v1/realms.proto
  protos/google/cloud/gaming/v1/realms_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1/game_server_clusters_service_client.ts
  src/v1/game_server_clusters_service_client_config.json
  src/v1/game_server_clusters_service_proto_list.json
  src/v1/game_server_configs_service_client.ts
  src/v1/game_server_configs_service_client_config.json
  src/v1/game_server_configs_service_proto_list.json
  src/v1/game_server_deployments_service_client.ts
  src/v1/game_server_deployments_service_client_config.json
  src/v1/game_server_deployments_service_proto_list.json
  src/v1/index.ts
  src/v1/realms_service_client.ts
  src/v1/realms_service_client_config.json
  src/v1/realms_service_proto_list.json
  synth.metadata
  synth.py
  test/gapic_game_server_clusters_service_v1.ts
  test/gapic_game_server_configs_service_v1.ts
  test/gapic_game_server_deployments_service_v1.ts
  test/gapic_realms_service_v1.ts
Labels: cla: yes

#112 build: stop passing credential file to secret manager
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: none

#113 build: use gapic-generator-typescript v1.0.7.
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
Labels: cla: yes, context: full

#114 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#115 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#116 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#118 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: gameservices, automerge, cla: yes, context: full
