Repository googleapis/nodejs-game-servers, pull requests merged in 2021-05, with the labels that each got.

#162 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: gameservices, automerge, cla: yes

#153 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .repo-metadata.json
  owlbot.py
  samples/test/clean.js
  samples/test/list_clusters.test.js
  src/index.ts
  src/v1/game_server_clusters_service_client.ts
  src/v1/game_server_configs_service_client.ts
  src/v1/game_server_deployments_service_client.ts
  src/v1/gapic_metadata.json
  src/v1/index.ts
  src/v1/realms_service_client.ts
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  test/gapic_game_server_clusters_service_v1.ts
  test/gapic_game_server_clusters_service_v1beta.ts
  test/gapic_game_server_configs_service_v1.ts
  test/gapic_game_server_configs_service_v1beta.ts
  test/gapic_game_server_deployments_service_v1.ts
  test/gapic_game_server_deployments_service_v1beta.ts
  test/gapic_realms_service_v1.ts
  test/gapic_realms_service_v1beta.ts
Labels: api: gameservices, cla: yes

#168 build: ignore CODEOWNERS file temporarily to test auto-approve.yml
  owlbot.py
Labels: api: gameservices, cla: yes

#170 build: add auto-approve
  .github/CODEOWNERS
  .github/auto-approve.yml
  owlbot.py
Labels: api: gameservices, cla: yes

#164 fix: use require() to load JSON protos
  src/v1beta/game_server_clusters_service_client.ts
  src/v1beta/game_server_configs_service_client.ts
  src/v1beta/game_server_deployments_service_client.ts
  src/v1beta/realms_service_client.ts
Labels: api: gameservices, automerge: exact, cla: yes, context: full
